apiVersion: v1
kind: Template
metadata:
  name: "3scale-custom-policy"
message: "3scale Custom Policy"
objects:

- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-policy

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: 3scale-custom-policy
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apicast-policy:latest
    source:
      git:
        uri: https://github.com/mgohashi/3scale-custom-policy.git
        ref: 'master'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'apicast-gateway-rhel8:${AMP_RELEASE}'

- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
    labels:
      app: apicast
    name: apicast-custom-policy
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'amp-apicast:latest'
    postCommit:
      args:
        - '--test'
        - '--lazy'
      command:
        - bin/apicast
    resources: {}
    runPolicy: Serial
    source:
      images:
        - from:
            kind: ImageStreamTag
            name: 'apicast-policy:latest'
          paths:
            # copy policy source code into the new image
            - destinationDir: policies
              sourcePath: /opt/app-root/policies/example
            # copy also installed dependencies to the policy folder, so they are vendored
            # - destinationDir: policies/example/0.1/resty/
            #   sourcePath: /opt/app-root/src/lua_modules/share/lua/5.1/resty/iputils.lua
      type: Dockerfile
      dockerfile: |
        FROM scratch
        COPY . src
        USER root

    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'amp-apicast:${AMP_RELEASE}'
      type: Docker
    triggers:
      - type: ConfigChange
      - type: ImageChange

parameters:
- name: AMP_RELEASE
  description: AMP Version (eg. 3scale2.9.1)
  value: 3scale2.9.1
